name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean test

      - name: Set absolute path to reports directory
        run: echo "REPORTS_PATH=${{ github.workspace }}/reports" >> $GITHUB_ENV

      - name: Archive HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: testing-report
          path: ${{ env.REPORTS_PATH }}/

      - name: Archive Log Files
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/
